name: GitHub App Token Generator
author: Jaryl Chng <git@jarylchng.com>
description: Easily generate a GitHub App integration access token to use for subsequent steps
inputs:
  key:
    description: Base64 encoded private key of the GitHub App
    required: true
  owner:
    description: owner/organization for which the token will be requested (defaults to current)
    required: false
    default: ""
outputs:
  token:
    description: An installation access token for the GitHub App on the requested organization (masked)
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.key }}
    - ${{ inputs.owner }}
branding:
  icon: unlock
  color: gray-dark
