name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Token
        id: generate_token
        uses: ./
        with:
          key: ${{ secrets.TEST_APP_KEY }}
          owner: ${{ secrets.TEST_OWNER }}
      - name: Test Masking
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
